version: "2.4"

volumes:
  redis-data:
  mongo-data:
  postgres-data:
  postgres-e2e-data:

services:

  api:
    build:
      context: server
      dockerfile: dev.Dockerfile
      args:
        NODE_VERSION:
        APP_VERSION:
    volumes:
      - ./server:/home/app
    links:
      - postgres:postgres.local
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  postgres-e2e:
    image: postgres
    restart: always
    volumes:
      - postgres-e2e-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"
    command: postgres -p 5433
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata2
      POSTGRES_USER: "e2e"
      POSTGRES_PASSWORD: "e2e"
      POSTGRES_DB: "e2e"

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
